# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/project-filters.yaml'
  - '.github/workflows/**'

# libraries
amplfi/architectures/:
  - *workflow
  - 'amplfi/architectures/**'
