# define filters for file changes
# to trigger unit tests

# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/workflows/unit-tests.yaml'
  - '.github/workflows/pre-commit.yaml'

# libraries
amplfi/architectures/:
  - *workflow
  - 'amplfi/architectures/**'
