# filter for changes
# to workflow
workflow: &workflow
  - '.github/filters.yaml'
  - '.github/project-filters.yaml'
  - '.github/workflows/**'

data:
  - *workflow
  - 'projects/data/**'
  - 'mldatafind/**'

train:
  - *workflow
  - 'projects/train/**'
  - 'amplfi/architectures/**'
  - 'ml4gw/**'
