# default prior for use with `IMRPhenomPv2`
class_path: amplfi.train.prior.AmplfiPrior
init_args:
  conversion_function: amplfi.train.conversion.precessing_to_lalsimulation_parameters
  priors:
    chirp_mass: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 1
        high: 3
        validate_args: false
    mass_ratio: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.5 
        high: 0.999
        validate_args: false
    distance: 
      class_path: ml4gw.distributions.UniformComovingVolume
      init_args:
        minimum:  10 
        maximum: 500 
        distance_type: "luminosity_distance"
        validate_args: false
    inclination: 
      class_path: ml4gw.distributions.Sine
      init_args:
        low: 0 
        high: 3.14159 
        validate_args: false
    phic: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 6.28318 
        validate_args: false
    a_1: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 0.4
        validate_args: false
    a_2: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 0.4
        validate_args: false
    tilt_1: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 3.14159  
        validate_args: false
    tilt_2: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 3.14159 
        validate_args: false
    phi_jl: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0 
        high: 6.28318 
        validate_args: false
    phi_12: 
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0
        high: 6.28318 
        validate_args: false
